version: "3"
services:
  eureka:
    image: bangjinseong/eureka:${BUILD_NUMBER}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_NUMBER
    ports:
      - "8761:8761"